local global = {
  opt = {
    encoding = "UTF-8",
    autowrite = true,
    breakindent = true,
    clipboard = "unnamed",
    cmdheight = 0,
    completeopt = { "menu", "menuone", "noselect" },
    conceallevel = 3,
    confirm = true,
    copyindent = true,
    cursorline = true,
    expandtab = true,
    fileencoding = "UTF-8",
    fillchars = [[eob: ,fold: ,foldopen:,foldsep: ,foldclose:]],
    foldenable = true,
    foldlevel = 99,
    foldlevelstart = 99,
    foldcolumn = vim.fn.has("nvim-0.9") == 1 and "1" or nil,
    formatoptions = "jcrolnt",
    grepformat = "%f:%l:%c:%m",
    grepprg = "rg --vimgrep",
    history = 100,
    ignorecase = true,
    inccommand = "nosplit",
    infercase = true,
    laststatus = 3,
    linebreak = true,
    list = true,
    mouse = "a",
    number = true,
    preserveindent = true,
    pumblend = 10,
    pumheight = 10,
    relativenumber = true,
    shiftwidth = 2,
    showmode = false,
    showtabline = 2,
    signcolumn = "yes",
    smartcase = true,
    splitbelow = true,
    splitright = true,
    tabstop = 2,
    termguicolors = true,
    timeoutlen = 500,
    undofile = true,
    updatetime = 200,
    virtualedit = "block",
    wrap = true,
    writebackup = false,
  },
  g = {
    mapleader = " ",
    maplocalleader = ",",
    max_file = { size = 1024 * 100, lines = 10000 },
    autoformat_enabled = true,
    autopairs_enabled = true,
    cmp_enabled = true,
    codelens_enable = true,
    diagnostics_mode = 3,
    highlighturnl_enabled = true,
    icons_enabled = true,
    inlay_hints_enabled = false,
    lsp_handlers_enabled = true,
    semantic_tokens_enabled = true,
    ui_notifications_enabled = true,
    git_worktrees = nil,
  },
}

for scope, table in pairs(global) do
  for setting, value in pairs(table) do
    vim[scope][setting] = value
  end
end
